/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MkSpinner {
    }
    interface MkStockFinder {
    }
    interface MkStockPrice {
        "stockSymbol": string;
    }
}
export interface MkStockFinderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMkStockFinderElement;
}
declare global {
    interface HTMLMkSpinnerElement extends Components.MkSpinner, HTMLStencilElement {
    }
    var HTMLMkSpinnerElement: {
        prototype: HTMLMkSpinnerElement;
        new (): HTMLMkSpinnerElement;
    };
    interface HTMLMkStockFinderElementEventMap {
        "mkSymbolSelected": string;
    }
    interface HTMLMkStockFinderElement extends Components.MkStockFinder, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMkStockFinderElementEventMap>(type: K, listener: (this: HTMLMkStockFinderElement, ev: MkStockFinderCustomEvent<HTMLMkStockFinderElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMkStockFinderElementEventMap>(type: K, listener: (this: HTMLMkStockFinderElement, ev: MkStockFinderCustomEvent<HTMLMkStockFinderElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMkStockFinderElement: {
        prototype: HTMLMkStockFinderElement;
        new (): HTMLMkStockFinderElement;
    };
    interface HTMLMkStockPriceElement extends Components.MkStockPrice, HTMLStencilElement {
    }
    var HTMLMkStockPriceElement: {
        prototype: HTMLMkStockPriceElement;
        new (): HTMLMkStockPriceElement;
    };
    interface HTMLElementTagNameMap {
        "mk-spinner": HTMLMkSpinnerElement;
        "mk-stock-finder": HTMLMkStockFinderElement;
        "mk-stock-price": HTMLMkStockPriceElement;
    }
}
declare namespace LocalJSX {
    interface MkSpinner {
    }
    interface MkStockFinder {
        "onMkSymbolSelected"?: (event: MkStockFinderCustomEvent<string>) => void;
    }
    interface MkStockPrice {
        "stockSymbol"?: string;
    }
    interface IntrinsicElements {
        "mk-spinner": MkSpinner;
        "mk-stock-finder": MkStockFinder;
        "mk-stock-price": MkStockPrice;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mk-spinner": LocalJSX.MkSpinner & JSXBase.HTMLAttributes<HTMLMkSpinnerElement>;
            "mk-stock-finder": LocalJSX.MkStockFinder & JSXBase.HTMLAttributes<HTMLMkStockFinderElement>;
            "mk-stock-price": LocalJSX.MkStockPrice & JSXBase.HTMLAttributes<HTMLMkStockPriceElement>;
        }
    }
}
